// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFy8DPRXI7cwHt_noJIXqQ9O6Rv4DJAD8',
    appId: '1:951665353248:web:aac8801c1b468361621245',
    messagingSenderId: '951665353248',
    projectId: 'flashchat-2ed29',
    authDomain: 'flashchat-2ed29.firebaseapp.com',
    storageBucket: 'flashchat-2ed29.appspot.com',
    measurementId: 'G-2VGSNHDBMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbavlxoj27KiDMDMaUdCf2Rd0DtY7fq8g',
    appId: '1:951665353248:android:21fbb267576a2355621245',
    messagingSenderId: '951665353248',
    projectId: 'flashchat-2ed29',
    storageBucket: 'flashchat-2ed29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiw26nFWN_z3GCgqZfADCPCutbzxXQWt8',
    appId: '1:951665353248:ios:a33a35a29a0c274d621245',
    messagingSenderId: '951665353248',
    projectId: 'flashchat-2ed29',
    storageBucket: 'flashchat-2ed29.appspot.com',
    iosBundleId: 'com.project.flashchat',
  );
}
